// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const authenticateAPIKey = `-- name: AuthenticateAPIKey :one
UPDATE api_keys
SET last_used_at = ?
WHERE token_hash = ? AND revoked_at IS NULL
RETURNING id, workspace_id, name, token_hash, created_at, last_used_at, revoked_at
`

type AuthenticateAPIKeyParams struct {
	LastUsedAt sql.NullString `json:"last_used_at"`
	TokenHash  string         `json:"token_hash"`
}

func (q *Queries) AuthenticateAPIKey(ctx context.Context, arg AuthenticateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, authenticateAPIKey, arg.LastUsedAt, arg.TokenHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, workspace_id, name, token_hash, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateAPIKeyParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	TokenHash   string `json:"token_hash"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
	)
	return err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, workspace_id, name, token_hash, created_at, last_used_at, revoked_at
FROM api_keys
WHERE workspace_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, workspaceID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET revoked_at = COALESCE(revoked_at, ?)
WHERE workspace_id = ? AND id = ?
`

type RevokeAPIKeyParams struct {
	RevokedAt   sql.NullString `json:"revoked_at"`
	WorkspaceID string         `json:"workspace_id"`
	ID          string         `json:"id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPIKey, arg.RevokedAt, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
