// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package sqlitedb

import (
	"context"
)

const countLinks = `-- name: CountLinks :one
SELECT count(*)
FROM links
WHERE workspace_id = ?
`

func (q *Queries) CountLinks(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinks, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :exec
INSERT INTO links (code, workspace_id, origin_url, created_at, visits)
VALUES (?, ?, ?, ?, ?)
`

type CreateLinkParams struct {
	Code        string `json:"code"`
	WorkspaceID string `json:"workspace_id"`
	OriginUrl   string `json:"origin_url"`
	CreatedAt   string `json:"created_at"`
	Visits      int64  `json:"visits"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) error {
	_, err := q.db.ExecContext(ctx, createLink,
		arg.Code,
		arg.WorkspaceID,
		arg.OriginUrl,
		arg.CreatedAt,
		arg.Visits,
	)
	return err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links
WHERE workspace_id = ? AND code = ?
`

type DeleteLinkParams struct {
	WorkspaceID string `json:"workspace_id"`
	Code        string `json:"code"`
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLink, arg.WorkspaceID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLinkByCode = `-- name: GetLinkByCode :one
SELECT code, workspace_id, origin_url, created_at, visits
FROM links
WHERE workspace_id = ? AND code = ?
`

type GetLinkByCodeParams struct {
	WorkspaceID string `json:"workspace_id"`
	Code        string `json:"code"`
}

func (q *Queries) GetLinkByCode(ctx context.Context, arg GetLinkByCodeParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByCode, arg.WorkspaceID, arg.Code)
	var i Link
	err := row.Scan(
		&i.Code,
		&i.WorkspaceID,
		&i.OriginUrl,
		&i.CreatedAt,
		&i.Visits,
	)
	return i, err
}

const listLinks = `-- name: ListLinks :many
SELECT code, workspace_id, origin_url, created_at, visits
FROM links
WHERE workspace_id = ?
ORDER BY created_at DESC, code DESC
LIMIT ? OFFSET ?
`

type ListLinksParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int64  `json:"limit"`
	Offset      int64  `json:"offset"`
}

func (q *Queries) ListLinks(ctx context.Context, arg ListLinksParams) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, listLinks, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.Code,
			&i.WorkspaceID,
			&i.OriginUrl,
			&i.CreatedAt,
			&i.Visits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveLink = `-- name: ResolveLink :one
UPDATE links
SET visits = visits + 1
WHERE code = ?
RETURNING code, workspace_id, origin_url, created_at, visits
`

func (q *Queries) ResolveLink(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRowContext(ctx, resolveLink, code)
	var i Link
	err := row.Scan(
		&i.Code,
		&i.WorkspaceID,
		&i.OriginUrl,
		&i.CreatedAt,
		&i.Visits,
	)
	return i, err
}

const updateLinkOrigin = `-- name: UpdateLinkOrigin :execrows
UPDATE links
SET origin_url = ?
WHERE workspace_id = ? AND code = ?
`

type UpdateLinkOriginParams struct {
	OriginUrl   string `json:"origin_url"`
	WorkspaceID string `json:"workspace_id"`
	Code        string `json:"code"`
}

func (q *Queries) UpdateLinkOrigin(ctx context.Context, arg UpdateLinkOriginParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLinkOrigin, arg.OriginUrl, arg.WorkspaceID, arg.Code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
