// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"database/sql"
)

type ApiKey struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	TokenHash   string         `json:"token_hash"`
	CreatedAt   string         `json:"created_at"`
	LastUsedAt  sql.NullString `json:"last_used_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

type Link struct {
	Code        string `json:"code"`
	WorkspaceID string `json:"workspace_id"`
	OriginUrl   string `json:"origin_url"`
	CreatedAt   string `json:"created_at"`
	Visits      int64  `json:"visits"`
}

type Workspace struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}
