// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlitedb

import (
	"context"
)

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, name
FROM workspaces
WHERE name = ?
`

type GetWorkspaceByNameRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetWorkspaceByName(ctx context.Context, name string) (GetWorkspaceByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByName, name)
	var i GetWorkspaceByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
